### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by matthewlal** [macchiato-framework/examples#7]
```
TypeError: Cannot read property 'call' of undefined
    at guestbook$db$messages (/mnt/c/Users/matth/Documents/Clojure/guestbook/target/out/guestbook/db.cljs:27:7)
    at /mnt/c/Users/matth/Documents/Clojure/guestbook/target/out/guestbook/routes.cljs:22:47
    at /mnt/c/Users/matth/Documents/Clojure/guestbook/target/out/guestbook/routes.js:80:3
    at /mnt/c/Users/matth/Documents/Clojure/guestbook/node_modules/synchronize/sync.js:281:10
```
I've copy and pasted the code from db.cljs and routes.cljs. Not sure why this error is occuring 🤔
@yogthos

**Comment by yogthos** [comment]
it looks like you might be missing some dependencies, take a look at the `project.clj`:

```clojure
:dependencies [... [macchiato/sql "0.0.1"]]

  :npm {:dependencies [[source-map-support "0.4.6"]
                       [sqlite3 "3.1.8"]
                       [synchronize "2.0.0"]]}
```

**Comment by matthewlal** [comment]
Thanks for the quick response @yogthos! I didn't see that dependency in the getting-started page 😕. Is it needed to interface with sqlite3?

Also, I unfortunately got the same error.

project.clj
```
(defproject guestbook "0.1.0-SNAPSHOT"
  :description "FIXME: write this!"
  :url "http://example.com/FIXME"
  :dependencies [[bidi "2.1.2"]
                 [com.cemerick/piggieback "0.2.2"]
                 [com.taoensso/timbre "4.10.0"]
                 [macchiato/hiccups "0.4.1"]
                 [macchiato/core "0.2.2"]
                 [macchiato/env "0.0.6"]
                 [macchiato/sql "0.0.1"]
                 [mount "0.1.11"]
                 [org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.908"]]
  :min-lein-version "2.0.0"
  :jvm-opts ^:replace ["-Xmx1g" "-server"]
  :plugins [[lein-doo "0.1.7"]
            [macchiato/lein-npm "0.6.3"]
            [lein-figwheel "0.5.13"]
            [lein-cljsbuild "1.1.5"]]
  :npm {:dependencies [[source-map-support "0.4.6"]
                       [sqlite3 "3.1.13"]
                       [synchronize "2.0.0"]]
        :write-package-json true}
  :source-paths ["src" "target/classes"]
  :clean-targets ["target"]
  :target-path "target"
  :profiles
  {:dev
   {:npm {:package {:main "target/out/guestbook.js"
                    :scripts {:start "node target/out/guestbook.js"}}}
    :dependencies [[figwheel-sidecar "0.5.13"]]
    :cljsbuild
    {:builds {:dev
              {:source-paths ["env/dev" "src"]
               :figwheel     true
               :compiler     {:main          guestbook.app
                              :output-to     "target/out/guestbook.js"
                              :output-dir    "target/out"
                              :target        :nodejs
                              :optimizations :none
                              :pretty-print  true
                              :source-map    true
                              :source-map-timestamp false}}}}
    :figwheel
    {:http-server-root "public"
     :nrepl-port 7000
     :reload-clj-files {:clj false :cljc true}
     :nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}
    :source-paths ["env/dev"]
    :repl-options {:init-ns user}}
   :test
   {:cljsbuild
    {:builds
     {:test
      {:source-paths ["env/test" "src" "test"]
       :compiler     {:main guestbook.app
                      :output-to     "target/test/guestbook.js"
                      :target        :nodejs
                      :optimizations :none
                      :pretty-print  true
                      :source-map    true}}}}
    :doo {:build "test"}}
   :release
   {:npm {:package {:main "target/release/guestbook.js"
                    :scripts {:start "node target/release/guestbook.js"}}}
    :cljsbuild
    {:builds
     {:release
      {:source-paths ["env/prod" "src"]
       :compiler     {:main          guestbook.app
                      :output-to     "target/release/guestbook.js"
                      :language-in   :ecmascript5
                      :target        :nodejs
                      :optimizations :simple
                      :pretty-print  false}}}}}}
  :aliases
  {"build" ["do"
            ["clean"]
            ["npm" "install"]
            ["figwheel" "dev"]]
   "package" ["do"
              ["clean"]
              ["npm" "install"]
              ["with-profile" "release" "npm" "init" "-y"]
              ["with-profile" "release" "cljsbuild" "once"]]
   "test" ["do"
           ["npm" "install"]
           ["with-profile" "test" "doo" "node"]]})

```

**Comment by yogthos** [comment]
You'll typically need a mix of ClojureScript and NPM dependencies. The error you're seeing basically means that a variable hasn't been loaded. Can you try and see if you have problems running the guestbook example in the repo?

**Comment by matthewlal** [comment]
I ran a clone of the guestbook sample in this repo, and it worked. After some trial and error with dependencies I found that the issue was using [org.clojure/clojurescript "LATEST"] in my project.clj instead of using [org.clojure/clojurescript "1.9.293"] like the getting-started page and this repo listed using. I just like using the latest versions 😅. I also didn't need [macchiato/sql "0.0.1"].

Thanks for the support @yogthos! 😄

**Comment by yogthos** [comment]
👍

**Comment by johnjelinek** [comment]
I get this error with the latest scaffolding:
`project.clj`:
```
(defproject guestbook "0.1.0-SNAPSHOT"
  :description "FIXME: write this!"
  :url "http://example.com/FIXME"
  :dependencies [[bidi "2.1.2"]
                 [com.cemerick/piggieback "0.2.2"]
                 [com.taoensso/timbre "4.10.0"]
                 [macchiato/hiccups "0.4.1"]
                 [macchiato/core "0.2.5"]
                 [macchiato/env "0.0.6"]
                 [mount "0.1.11"]
                 [org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.9.946"]
                 ;; needed for JDK 9 compatibility
                 [javax.xml.bind/jaxb-api "2.3.0"]]
  :min-lein-version "2.0.0"
  :jvm-opts ^:replace ["-Xmx1g" "-server"]
  :plugins [[lein-doo "0.1.7"]
            [macchiato/lein-npm "0.6.3"]
            [lein-figwheel "0.5.14"]
            [lein-cljsbuild "1.1.5"]]
  :npm {:dependencies [[source-map-support "0.4.6"]
                       [sqlite3 "3.1.8"]
                       [synchronize "2.0.0"]]
        :write-package-json true}
  :source-paths ["src" "target/classes"]
  :clean-targets ["target"]
  :target-path "target"
  :profiles
  {:dev
   {:npm {:package {:main "target/out/guestbook.js"
                    :scripts {:start "node target/out/guestbook.js"}}}
    :dependencies [[figwheel-sidecar "0.5.14"]]
    :cljsbuild
    {:builds {:dev
              {:source-paths ["env/dev" "src"]
               :figwheel     true
               :compiler     {:main          guestbook.app
                              :output-to     "target/out/guestbook.js"
                              :output-dir    "target/out"
                              :target        :nodejs
                              :optimizations :none
                              :pretty-print  true
                              :source-map    true
                              :source-map-timestamp false}}}}
    :figwheel
    {:http-server-root "public"
     :nrepl-port 7000
     :reload-clj-files {:clj false :cljc true}
     :nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}
    :source-paths ["env/dev"]
    :repl-options {:init-ns user}}
   :test
   {:cljsbuild
    {:builds
     {:test
      {:source-paths ["env/test" "src" "test"]
       :compiler     {:main guestbook.app
                      :output-to     "target/test/guestbook.js"
                      :target        :nodejs
                      :optimizations :none
                      :pretty-print  true
                      :source-map    true}}}}
    :doo {:build "test"}}
   :release
   {:npm {:package {:main "target/release/guestbook.js"
                    :scripts {:start "node target/release/guestbook.js"}}}
    :cljsbuild
    {:builds
     {:release
      {:source-paths ["env/prod" "src"]
       :compiler     {:main          guestbook.app
                      :output-to     "target/release/guestbook.js"
                      :language-in   :ecmascript5
                      :target        :nodejs
                      :optimizations :simple
                      :pretty-print  false}}}}}}
  :aliases
  {"build" ["do"
            ["clean"]
            ["npm" "install"]
            ["figwheel" "dev"]]
   "package" ["do"
              ["clean"]
              ["npm" "install"]
              ["with-profile" "release" "npm" "init" "-y"]
              ["with-profile" "release" "cljsbuild" "once"]]
   "test" ["do"
           ["npm" "install"]
           ["with-profile" "test" "doo" "node"]]})
```

`db.cljs`:
```
(ns guestbook.db
  (:require
    [cljs.nodejs :as node]
    [mount.core :refer [defstate]]))

(def sync (node/require "synchronize"))

(def sqlite3 (node/require "sqlite3"))

(defstate db
  :start (let [db (sqlite3.Database. ":memory:")]
           (.run
             db
             "CREATE TABLE guestbook
                         (id INTEGER PRIMARY KEY AUTOINCREMENT,
                          name VARCHAR(30),
                          message VARCHAR(200),
                          time TIMESTAMP DEFAULT CURRENT_TIMESTAMP);"))
  :stop (.close @db))

(defn add-message [{:keys [name message]}]
  (.run @db "INSERT INTO guestbook (name, message) VALUES (?, ?)" #js [name message]))

(defn messages []
  (-> @db
      (.all "SELECT * FROM guestbook" (sync.defer))
      (sync.await)
      (js->clj :keywordize-keys true)))
```

`routes.cljs`:
```
(ns guestbook.routes
  (:require
    [bidi.bidi :as bidi]
    [hiccups.runtime]
    [guestbook.db :as db]
    [macchiato.middleware.anti-forgery :as af]
    [macchiato.util.response :as r]
    [cljs.nodejs :as node])
  (:require-macros
    [hiccups.core :refer [html]]))

(def sync (node/require "synchronize"))

(defn home [req res raise]
  (sync.fiber
    #(let [af-token af/*anti-forgery-token*]
       (->
         [:html
          [:body
           [:h2 "Messages"]
           [:ul
            (for [{:keys [name message time]} (db/messages)]
              [:li name " says " message " at " time])]
           [:hr]
           [:h2 "leave a message"]
           [:form {:method "POST" :action "/message"}
            [:input
             {:type        :text
              :name        "name"
              :placeholder "name"}]
            [:input
             {:type  "hidden"
              :name  "__anti-forgery-token"
              :value af-token}]
            [:input
             {:type        :text
              :name        "message"
              :placeholder "message"}]
            [:input
             {:type  :submit
              :value "add message"}]]]]
         (html)
         (r/ok)
         (r/content-type "text/html")
         (res)))))

(defn message [req res raise]
  (db/add-message (select-keys (:params req) [:name :message]))
  (res (r/found "/")))

(defn not-found [req res raise]
  (-> (html
        [:html
         [:body
          [:h2 (:uri req) " was not found"]]])
      (r/not-found)
      (r/content-type "text/html")
      (res)))

(def routes
  ["/" {""        {:get home}
        "message" {:post message}}])

(defn router [req res raise]
  ((:handler (bidi/match-route* routes (:uri req) req) not-found)
    req res raise))
```

`error`:
```
INFO [guestbook.core:19] - guestbook started on 127.0.0.1 : 8080
Figwheel: trying to open cljs reload socket
Figwheel: socket connection established
TypeError: Cannot read property 'call' of undefined
    at guestbook$db$messages (/home/john/guestbook/target/out/guestbook/db.cljs:27:7)
    at /home/john/guestbook/target/out/guestbook/routes.cljs:22:47
    at /home/john/guestbook/target/out/guestbook/routes.js:80:3
    at /home/john/guestbook/node_modules/synchronize/sync.js:281:10
```

**Comment by yogthos** [comment]
It looks like there's a variable missing, I can take a look tomorrow if you can link to your version of the project. Could be that a variable is used before it's declared?

**Comment by yogthos** [comment]
It looks like there's a variable missing, I can take a look tomorrow if you can link to your version of the project. Could be that a variable is used before it's declared?

**Comment by johnjelinek** [comment]
I've got a repro in the repl:
```
dev:guestbook.db=> (messages)
#object[TypeError TypeError: Cannot read property 'call' of undefined]
TypeError: Cannot read property 'call' of undefined
    at guestbook$db$messages (/home/john/guestbook/target/out/guestbook/db.cljs:27:7)
    at eval (eval at figwheel$client$utils$eval_helper (/home/john/guestbook/target/out/figwheel/client/utils.cljs:77:5), <anonymous>:1:248)
    at eval (eval at figwheel$client$utils$eval_helper (/home/john/guestbook/target/out/figwheel/client/utils.cljs:77:5), <anonymous>:9:3)
    at eval (eval at figwheel$client$utils$eval_helper (/home/john/guestbook/target/out/figwheel/client/utils.cljs:77:5), <anonymous>:14:4)
    at figwheel$client$utils$eval_helper (/home/john/guestbook/target/out/figwheel/client/utils.cljs:77:5)
```

**Comment by johnjelinek** [comment]
```
dev:guestbook.db=> (-> @db (.all "SELECT * FROM guestbook" (sync.defer)))
#object[Error Error: no current Fiber, defer can't be used without Fiber!]
Error: no current Fiber, defer can't be used without Fiber!
    at sync.defer (/home/john/guestbook/node_modules/synchronize/sync.js:63:28)
    at eval (eval at figwheel$client$utils$eval_helper (/home/john/guestbook/target/out/figwheel/client/utils.cljs:77:5), <anonymous>:1:323)
    at eval (eval at figwheel$client$utils$eval_helper (/home/john/guestbook/target/out/figwheel/client/utils.cljs:77:5), <anonymous>:9:3)
    at eval (eval at figwheel$client$utils$eval_helper (/home/john/guestbook/target/out/figwheel/client/utils.cljs:77:5), <anonymous>:14:4)
    at figwheel$client$utils$eval_helper (/home/john/guestbook/target/out/figwheel/client/utils.cljs:77:5)
```

**Comment by yogthos** [comment]
The way the fibers work is a bit fiddly, you have to be inside a `sync.fiber` block to call them. It seemed like a promising approach originally, but I prefer using core.async instead now.

**Comment by yogthos** [comment]
ok I updated the guestbook project to the latest template, and got rid of the fibers as they're just adding confusion

**Comment by johnjelinek** [comment]
I guess [getting started](https://macchiato-framework.github.io/docs/getting-started) should be updated as well ... maybe I can contribute a PR for that.

**Comment by yogthos** [comment]
sounds great, note that you'd want to make changes on the `src` branch, the master gets built from it automatically.

**Comment by johnjelinek** [comment]
https://github.com/macchiato-framework/macchiato-framework.github.io/pull/11

**Comment by yogthos** [comment]
👍
